/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import PagSeguroBridge from 'react-native-pagseguro-bridge';

export default function App() {
  const testePrint = async () => {
    try {
      const result = await PagSeguroBridge.printFile(
        '/storage/emulated/0/dogs.jpg',
        4,
        1000,
      );
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆PagSeguroBridge example☆</Text>
      <Text style={styles.instructions}>Abra o console e teste</Text>
      <Button onPress={testePrint} title="Teste" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
